# Refer to https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml for more information.
# Lint directives.
lint: 
  # Linter rules.
  # Run `protolint list` to see all available rules.
  rules: 
    all_default: true
